spring.application.name=-1

spring.datasource.url=jdbc:mysql://localhost:3306/td
spring.datasource.username=root
spring.datasource.password=Sunny@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

spring.thymeleaf.cache=false


upstox.access-token=eyJ0eXAiOiJKV1QiLCJrZXlfaWQiOiJza192MS4wIiwiYWxnIjoiSFMyNTYifQ.eyJzdWIiOiIzVUFWUUsiLCJqdGkiOiI2YWJiODNlMGY0ZjlhMTMyMzI4OGY2NmEiLCJpc011bHRpQ2xpZW50IjpmYWxzZSwiaXNQbHVzUGxhbiI6ZmFsc2UsImlhdCI6MTc5MDY3Mzg4OCwiaXNzIjoidWRhcGktZ2F0ZXdheS1zZXJ2aWNlIiwiZXhwIjoxNzkwNzE5MjAwfQ.OivumntClsVNKDGjTKjUK2RBrqpHzq3GB1ItEThm0H0