spring.application.name=school_management_system

server.address=0.0.0.0
server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/school_demo
spring.datasource.username=root
spring.datasource.password=Sunny@123

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=112003rajasingh@gmail.com
spring.mail.password=uuzm gdfy wjgt synm

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

twilio.account.sid=YOUR_TWILIO_ACCOUNT_SID
twilio.auth.token=YOUR_TWILIO_AUTH_TOKEN
twilio.whatsapp.from=whatsapp:+91457457457

razorpay.key-id=rzp_test_TNFyzLHnJPSzBm
razorpay.key-secret=empXQsRWScYliUlnC7yB9ACd
