spring.application.name=-3

spring.datasource.url=jdbc:mysql://localhost:3306/td
spring.datasource.username=root
spring.datasource.password=Sunny@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

spring.thymeleaf.cache=false

spring.security.user.name=u
spring.security.user.password=u

upstox.access-token=eyJ0eXAiOiJKV1QiLCJrZXlfaWQiOiJza192MS4wIiwiYWxnIjoiSFMyNTYifQ.eyJzdWIiOiIzVUFWUUsiLCJqdGkiOiI2YWMzNjFjMWFhYjM3MzY3NzYwMWU2NmQiLCJpc011bHRpQ2xpZW50IjpmYWxzZSwiaXNQbHVzUGxhbiI6ZmFsc2UsImlhdCI6MTc5MTE4OTQ0MSwiaXNzIjoidWRhcGktZ2F0ZXdheS1zZXJ2aWNlIiwiZXhwIjoxNzkxMjM3NjAwfQ.pX6l9gZ7MEb96ebWmJ44MMZJJm95_bp4-xC77avvcAs