spring.application.name=-1

spring.datasource.url=jdbc:mysql://localhost:3306/td
spring.datasource.username=root
spring.datasource.password=Sunny@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

spring.thymeleaf.cache=false


upstox.access-token=eyJ0eXAiOiJKV1QiLCJrZXlfaWQiOiJza192MS4wIiwiYWxnIjoiSFMyNTYifQ.eyJzdWIiOiIzVUFWUUsiLCJqdGkiOiI2YWJhMjk1NWE2ZTQxZDVmOTk0ZDQyYzQiLCJpc011bHRpQ2xpZW50IjpmYWxzZSwiaXNQbHVzUGxhbiI6ZmFsc2UsImlhdCI6MTc5MDU4NTE3MywiaXNzIjoidWRhcGktZ2F0ZXdheS1zZXJ2aWNlIiwiZXhwIjoxNzkwNjMyODAwfQ.fDxxfXR5uPyDLDF4VOIn6n4NN0Two61CYWKKLzyE4M8